version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  users-api:
    build: ./users-api
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  auth-api:
    build: ./auth-api
    ports:
      - "8082:8080"

  todos-api:
    build: ./todos-api
    ports:
      - "8083:8080"
    depends_on:
      - redis

  log-processor:
    build: ./log-message-processor
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-api
      - users-api
      - todos-api
