name: Frontend CI/CD - Azure Container Apps

on:
  push:
    branches:
      - master
      - main
      - dev 
      - infra/feature/terraform-infra-implementation
    paths:
      - 'frontend/**'

env:
  REGISTRY: acrmicroserviceappdeva6b3d4b9.azurecr.io
  IMAGE_NAME: frontend
  RESOURCE_GROUP: rg-microservice-dev
  CONTAINER_APP: ca-frontend-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package.json'
      
      - name: Install dependencies and build
        run: |
          cd frontend
          npm ci --legacy-peer-deps
          npm run build
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name acrmicroserviceappdeva6b3d4b9
      
      - name: Build and push Docker image
        run: |
          cd frontend
          IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          
          # Also tag as latest for convenience
          docker tag $IMAGE_TAG ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      
      - name: Deploy to Azure Container Apps
        run: |
          IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          az containerapp update \
            --name ${{ env.CONTAINER_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image $IMAGE_TAG
