name: Infrastructure Pipeline

on:
  push:
    branches: [main, master, develop, fix/login-and-todo]
    paths: ['infrastructure/**']
  pull_request:
    branches: [main, master]
    paths: ['infrastructure/**']

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: |
        cd infrastructure
        terraform init

    - name: Terraform Plan
      run: |
        cd infrastructure
        terraform plan -no-color
      if: github.event_name == 'pull_request'

    - name: Terraform Apply
      run: |
        cd infrastructure
        terraform apply -auto-approve -no-color
      if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/fix/login-and-todo') && github.event_name == 'push'