name: Log Message Processor CI

on:
  push:
    branches:
      - master
    paths:
      - 'log-message-processor/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for Log-Message-Processor
        run: |
          docker build -t log-message-processor ./log-message-processor

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VM_IP_KEY }} >> ~/.ssh/known_hosts

      - name: Pull latest code on remote server
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD_KEY }}" ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_IP_KEY }} "\
            cd /opt/microservice-app-example && \
            sudo git pull --no-rebase origin master \
          "

      - name: Rebuild and restart log-message-processor container
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD_KEY }}" ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_IP_KEY }} "\
            cd /opt/microservice-app-example && \
            sudo docker-compose up -d --build --force-recreate log-message-processor \
          "