name: CI Todos API
on:
  push:
    branches: [ dev, feature/* ]
    paths: [ 'todos-api/**' ]
  pull_request:
    branches: [ dev ]
    paths: [ 'todos-api/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd todos-api && npm ci
      - name: Run tests
        run: cd todos-api && npm test || echo "No tests found"
      - name: Build Docker image
        run: docker build -t naysp/todos-api:${{ github.sha }} ./todos-api
