name: Users API CI/CD - Azure Container Apps

on:
  push:
    branches:
      - master
      - main
      - dev
      - fix/login-and-todo
    paths:
      - 'users-api/**'

env:
  REGISTRY: acrmicroserviceappdeva6b3d4b9.azurecr.io
  IMAGE_NAME: users-api
  RESOURCE_GROUP: rg-microservice-dev
  CONTAINER_APP: ca-users-api-dev

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('users-api/pom.xml') }}
      
      - name: Test Users API
        run: |
          cd users-api
          mvn clean compile test
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/fix/login-and-todo'
      
      - name: Log in to Azure Container Registry
        run: az acr login --name acrmicroserviceappdeva6b3d4b9
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/fix/login-and-todo'
      
      - name: Build and push Docker image
        run: |
          cd users-api
          IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          
          # Also tag as latest
          docker tag $IMAGE_TAG ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/fix/login-and-todo'
      
      - name: Deploy to Azure Container Apps
        run: |
          IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          az containerapp update \
            --name ${{ env.CONTAINER_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image $IMAGE_TAG
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/fix/login-and-todo'