name: Users API CI/CD - Azure Container Apps
on:
  push:
    branches:
      - master
      - main
      - dev
      - infra/feature/terraform-infra-implementation
    paths:
      - 'users-api/**'

env:
  REGISTRY: acrmicroserviceappdeva6b3d4b9.azurecr.io
  IMAGE_NAME: users-api
  RESOURCE_GROUP: rg-microservice-dev
  CONTAINER_APP: ca-users-api-dev
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('users-api/pom.xml') }}
      
      - name: Test Users API
        run: |
          cd users-api
          mvn clean compile test -Dspring.profiles.active=test -Dmaven.test.failure.ignore=false
      
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          cd users-api
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Update Container App
        run: |
          az containerapp update \
            --name ${{ env.CONTAINER_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}